name: Release

on:
  push:
    branches:
      - main

concurrency: ci-${{ github.ref }}-release

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run Gradle Publish
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: publish
